# Generated by Django 5.1.1 on 2025-10-16 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=1000)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quilometragem', models.IntegerField(help_text='Quilometragem em KM')),
                ('tipo_anuncio', models.CharField(choices=[('venda', 'Venda'), ('troca', 'Troca')], default='venda', max_length=10)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('vendido', 'Vendido'), ('pausado', 'Pausado')], default='ativo', max_length=10)),
                ('telefone', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='veiculo.veiculo')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
